### ISSUE TITLE
[Craft 4] Error when accepting cookies on iOS devices

### ISSUE THREAD

**Issue by ebarbe-globalia** [elleracompany/craft-cookie-consent#116]
**Problem:** 
When clicking on `Accept All` on iOS devices, the page is redirected to the action url for cookie consent, and just the string `true` is displayed. The form seems to be submitted onto the same page instead of using an ajax request. 

**Steps to reproduce:** 
- Add the hook `{% hook 'after-body-start' %}` to your template.
- Activate `Load plugin default JS assets.` on plugin configuration.
- Open the page on an iOS device
- Click on `Accept All` 
Page displays a `true` string instead of the current template.
 
**Version details:**
- Craft 4.12.0
- GDPR Cookie Consent 4.0.4

**Comment by JulieVelghe** [comment]
@jellingsen some more info on this one, since it happens on desktop as well.
the display true only seems to happen once, the first time I open a (sub)site after the cookie consent is activated in the backend.
When I put my cursor in the url part of the browser and press enter (not ctrl+f5, that doesn't work), then the 'true' goes away and i'm back on the site.

I can then browse the site without constantly getting the popup, but when I do open the popup, and I try to save any setting, it doesn't seem to save anything. The page gets reloaded, I can see the consents in the admin, but when re-opening the popup, nothing is checked.
![image](https://github.com/user-attachments/assets/3685f654-523d-4169-ab85-f9b4e552e141)

**Comment by jellingsen** [comment]
Thank you for the additional information, @JulieVelghe. I'll try to reproduce now, and see what I can find.

**Comment by jellingsen** [comment]
@JulieVelghe 

> I can then browse the site without constantly getting the popup, but when I do open the popup, and I try to save any setting, it doesn't seem to save anything. The page gets reloaded, I can see the consents in the admin, but when re-opening the popup, nothing is checked.

Do you get a CORS-error in the network tab in developer tools when this happens?

**Comment by JulieVelghe** [comment]
@jellingsen I did get one, but I've adjusted my htaccess file and no longer get that cors error, but the cookie issues remains.

my htaccess is like this:
```
<IfModule mod_headers.c>
    SetEnvIf Origin "http(s)?://(www\.|preview\.|staging\.|local\.)?(busleydenatheneum.be|babotaniek.be|bacaputsteen.be|badebeemden.be|bahbo5.be|banekkerspoel.be|bapitzemburg.be|bastassart.be|bazandpoort.be|baverpleegkunde.be)$" AccessControlAllowOrigin=$0
    Header add Access-Control-Allow-Origin %{AccessControlAllowOrigin}e env=AccessControlAllowOrigin
    Header set Access-Control-Allow-Credentials true
    Header set Access-Control-Allow-Headers *
    Header merge Vary Origin
</IfModule>

<IfModule mod_headers.c>
    Header always set Permissions-Policy: interest-cohort=()
</IfModule>

<IfModule mod_rewrite.c>
    RewriteEngine On

    # Redirect www to non-www
    RewriteCond %{HTTP_HOST} ^www\.(busleydenatheneum.be|babotaniek.be|bacaputsteen.be|badebeemden.be|bahbo5.be|banekkerspoel.be|bapitzemburg.be|bastassart.be|bazandpoort.be|baverpleegkunde.be)$ [NC]
    RewriteRule ^(.*)$ https://%1/$1 [R=301,L]

    # Redirect bahbo5.be to baverpleegkunde.be
    RewriteCond %{HTTP_HOST} ^bahbo5\.be$ [OR]
    RewriteCond %{HTTP_HOST} ^www\.bahbo5\.be$
    RewriteRule ^(.*)$ https://baverpleegkunde.be/$1 [L,R=301]

    # Redirect staging bahbo5.be to baverpleegkunde.be
    RewriteCond %{HTTP_HOST} ^staging\.bahbo5\.be$
    RewriteRule ^(.*)$ https://staging.baverpleegkunde.be/$1 [L,R=301]

    # Send would-be 404 requests to Craft
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !^/(favicon\.ico|apple-touch-icon.*\.png)$ [NC]
    RewriteRule (.+) index.php?p=$1 [QSA,L]
</IfModule>
```
I did notice, when I change my cookie preferences on the main site, and than go to another page and check them again, the changes remain. So apart from that 'true'-bug, the cookie preferences seem to be saved on the main site.

**Comment by jellingsen** [comment]
@JulieVelghe is this a localhost-issue, or do you experience it on production as well? The only way I'm able to reproduce what you are explaining is hen the site is opened with http and posts to https and thus gets a CORS-error.

@ebarbe-globalia I'm unfortunatly unable to reproduce locally on my iPhone 14 with ddev over the local network. Could you point me to the site that you experience this so I can have a look at it directly?

**Comment by JulieVelghe** [comment]
Hi @jellingsen , I'm having the issue on local and on the staging and production as well. 
On production I have the constant popup, on local and staging I have the 'true'-bug, as I've added the new hook on those environments.
Here is the staging link for the main site :  https://staging.busleydenatheneum.be/
and for a subsite: https://staging.banekkerspoel.be/
both have https.

**Comment by JulieVelghe** [comment]
hi @jellingsen , 
I've been messing around my staging environment some more. I tried to invalidate the consents, which I would think means a reset of sorts?
On the main site, the cookies are being saved perfectly, no strangs things there. On the subsite however, I'm getting the constant popup again. You can see it in action on the staging url's I put above.

So thats a setup with craft 4.13.9 and cookie consent 4.0.4, and the extra after-body-start hook and  Header set Access-Control-Allow-Headers * and https.

I've just looked at my production, setup there is also https, craft 4.13.9, cookie consent 4.0.4, but there I don't have the the body start hook, headers in htaccess aren't adjusted and I haven't yet invalidated the consents there.
Issues seem the same as on the staging. Main site seems to save the cookies, subsites get constant popups.

I think the 'true'-bug only happens the one time when you freshly activate the cookie consent for a site.

**Comment by jellingsen** [comment]
Hi @JulieVelghe
Thank you for debugging information. It looks like the subsite is not passing the CraftSessionId cookie with the ajax endpoint - can you confirm that you observe the same behavior?

**Comment by JulieVelghe** [comment]
@jellingsen for some more comparisons, we have another site, [https://ilvo.vlaanderen](https://ilvo.vlaanderen.be/](https://ilvo.vlaanderen.be/en), where we also have the cookie consent 4.0.4, but an older craft (4.12.8), there everything still works fine.

**Comment by JulieVelghe** [comment]
@jellingsen how can I check that behaviour?

when I look in the cookies, I can see the CraftSessionId cookie for the subsite:
![image](https://github.com/user-attachments/assets/fb6ea502-8df7-48c4-8898-091b13aefea6)

Where do I check the ajax endpoint exactly?

**Comment by jellingsen** [comment]
Yeah, the cookie is set, but its not passed with the request headers it seems. 
<img width="617" alt="Screenshot 2025-01-09 at 12 12 57" src="https://github.com/user-attachments/assets/f4e19310-ff23-42a3-8950-0a19adf1de08" />
<img width="582" alt="Screenshot 2025-01-09 at 12 12 28" src="https://github.com/user-attachments/assets/ffbdae0e-a5c0-4a1a-bc6b-1d1bc056aa68" />

**Comment by JulieVelghe** [comment]
@jellingsen , I can confirm the behaviour. Below some screenshots:

request cookies from main site:
![image](https://github.com/user-attachments/assets/ee26183a-70a7-42b1-90e9-f863c67bada2)

Subsite doesn't seem to have any request cookies at all:
![image](https://github.com/user-attachments/assets/4d8abbee-2950-4a84-9bdd-0f1216a6b26b)

Headers on the main site:
![image](https://github.com/user-attachments/assets/8a1fbbca-6702-49b1-a63c-a9c0fdb88238)

headers on the subsite (indeed missing the craft session id):
![image](https://github.com/user-attachments/assets/19320305-3944-4cd8-8760-2eabbec64f56)

**Comment by jellingsen** [comment]
Yeah, ofcourse its not sending the cookies - its sending the request to another domain, the main site.. It must send it to the subsite..

**Comment by JulieVelghe** [comment]
@jellingsen this is not something that we can fix, but has to be fixed by you then?

**Comment by ebarbe-globalia** [comment]
> @ebarbe-globalia I'm unfortunatly unable to reproduce locally on my iPhone 14 with ddev over the local network. Could you point me to the site that you experience this so I can have a look at it directly?

@jellingsen We are experiencing this issue with [https://www.jsheld.com/](https://www.jsheld.com/)

**Comment by JulieVelghe** [comment]
hello @jellingsen , any news on a possible fix for this issue?

**Comment by jellingsen** [comment]
@JulieVelghe i'm trying to reproduce now, but my multisite setup sends the request to the multisite domain, not to the main domain. Have you done some custom template coding? What is the content of your data-url-attribute in the form tag?

**Comment by JulieVelghe** [comment]
hi @jellingsen , we do indeed use a custom template code. Below is the twig:

```
<section id="elc-cookie-consent" class="elc-small{% if craft.cookieConsent.consentGiven == 1 %} elc-hidden{% endif %}">
    <form id="elc-cookie-consent-form" action="" data-url="{{ actionUrl() }}" {{ craft.cookieConsent.getRefreshDataAttr }} data-show="{{ siteUrl() }}/cookie-consent/show" method="post" accept-charset="UTF-8">
        <input type="hidden" name="action" value="cookie-consent/consent/update">
        <input type="hidden" name="site_id" value="{{ currentSite.id }}">
        {% if craft.cookieConsent.consentGiven == 1 %}
            <input type="hidden" name="uid" value="{{ craft.cookieConsent.getUid }}">
        {% endif %}
        {{ csrfInput() }}
        <header class="elc-header">
            <h2>{{ craft.cookieConsent.headline|t('cookie-consent') }}</h2>
            <p>{{ craft.cookieConsent.description|t('cookie-consent') }}</p>
        </header>
        <div id="elc-cookie-consent-settings"{% if craft.cookieConsent.hideCheckboxes %} class="elc-hide-when-small"{% endif %}>
            {% for group in craft.cookieConsent.groups %}
                <div class="elc-cookie-group">
                    <div class="elc-row elc-cookie-headline">
                        <input type="checkbox" id="elc-checkbox-{{loop.index}}" class="elc-cookie-checkbox" name="group-{{ group.slug }}"{{ group.required == 1 ? ' disabled="disabled"' : "" }}{{ ((craft.cookieConsent.consentGiven != 1 and group.default == 1) or craft.cookieConsent.getConsent(group.slug)) ? " checked" : "" }}>
                        <label class="elc-cookie-name" for="elc-checkbox-{{loop.index}}">{{ group.name|t('cookie-consent') }}{% if group.required == 1 %} <small>({{ "Required"|t('cookie-consent') }})</small>{% endif %}</label>
                    </div>
                    {% if group.description %}
                        <div class="elc-row elc-cookie-description">
                            {{ group.description|t('cookie-consent') }}
                        </div>
                    {% endif %}
                    {% for cookie in group.cookies | json_decode %}
                        <div class="elc-cookie">
                            <div class="elc-cookie-field">
                                <strong>{{ "Name"|t('cookie-consent') }}</strong>: {{ cookie.name|t('cookie-consent') }}
                            </div>
                            {% if cookie.description %}
                                <div class="elc-cookie-field">
                                    <strong>{{ "Description"|t('cookie-consent') }}</strong>: {{ cookie.description|t('cookie-consent') | md | striptags('<a>') | raw }}
                                </div>
                            {% endif %}
                            {% if cookie.provider %}
                                <div class="elc-cookie-field">
                                    <strong>{{ "Provider"|t('cookie-consent') }}</strong>: {{ cookie.provider|t('cookie-consent') }}
                                </div>
                            {% endif %}
                            {% if cookie.expiry %}
                                <div class="elc-cookie-field">
                                    <strong>{{ "Expiry"|t('cookie-consent') }}</strong>: {{ cookie.expiry|t('cookie-consent') }}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
        <div class="button-container">
            <a href="#" id="elc-detail-link">{{ "Details"|t('cookie-consent') }}</a>
            <a href="#" id="elc-hide-detail-link">{{ "Hide details"|t('cookie-consent') }}</a>
            <button class="c-button" id="elc-save-link" type="submit">
                <span class="c-button__label">{{ "Save"|t('cookie-consent') }}</span>
            </button>
            {% if (craft.cookieConsent.showAcceptAllButton == 1) %}
                <button class="c-button" id="elc-accept-link" type="submit">
                    <span class="c-button__label">{{ "Save"|t('cookie-consent') }}</span>
                </button>
                <button class="c-button" id="elc-accept-all-link" type="submit">
                    <span class="c-button__label">{{ "Accept all"|t('cookie-consent') }}</span>
                </button>
            {% else %}
                <button class="c-button" id="elc-accept-link" type="submit">
                    <span class="c-button__label">{{ "OK"|t('cookie-consent') }}</span>
                </button>
            {% endif %}
        </div>
    </form>
</section>
```

**Comment by jellingsen** [comment]
That looks correct, but `actionUrl()` should resolve the multisite URL with the action path. Can you check the multisite setup and the network configurations?

This is from my testing environment:

<img width="305" alt="Image" src="https://github.com/user-attachments/assets/c274776a-71b4-4263-9d52-cfc55286368b" />
<img width="1338" alt="Image" src="https://github.com/user-attachments/assets/fdbd984c-5619-4229-92ae-2f6157958729" />
<img width="482" alt="Image" src="https://github.com/user-attachments/assets/307845a1-10be-4453-beed-d6644eee3a29" />
<img width="467" alt="Image" src="https://github.com/user-attachments/assets/903f85e2-f7a8-4513-8433-60a54ec43479" />

**Comment by JulieVelghe** [comment]
@jellingsen it looks like it doesn't resolve correctly. The network setup looks fine. The form on the frontend does not. 
First, here is a screenshot of the form on the primary site:

![Image](https://github.com/user-attachments/assets/cb03d42a-69f1-4a68-9f15-7a19cf9921d3)

and below the form on a subsite:

![Image](https://github.com/user-attachments/assets/55321d0c-7a22-42e8-b70a-a62e2fae7b19)

**Comment by jellingsen** [comment]
I'm not sure how to help you debug further.

The data-show-attribute does look correct tho, and that's using siteUrl(). You could update data-url to `siteUrl() . "/index.php?p=action"` and see if that helps.

**Comment by JulieVelghe** [comment]
@jellingsen I've changed the data-url and that seems to work well. Thank you!

**Comment by jellingsen** [comment]
@ebarbe-globalia I checked now, but I cant see "Accept all" - I guess you've disabled it for now?

**Comment by jellingsen** [comment]
Fixed in 5.1.0. Two changes address this: the banner JavaScript was fully rewritten (modern event binding, fetch), and the consent endpoint now degrades gracefully — if the form is ever submitted natively instead of via ajax, the endpoint redirects the visitor back to the page they came from instead of showing a raw response body. One note: since 5.1.0 the default banner no longer embeds a CSRF token (it's fetched via ajax to keep pages cacheable), so if you use a custom template and need the non-JS fallback, keep {{ csrfInput() }} in your form. Please reopen if you can still reproduce this on an iOS device with 5.1.0.
